---
title: "Apoptosis-related gene set evolution"
output: 
  html_document:
    df_print: paged
author: "Sabrina Pankey"
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,results="hide", message=FALSE, fig.height=10,fig.width=10)

```

```{r import}
require(phytools)
library(reshape2)
packageVersion("phytools")

setwd("~/Desktop/R /Hydractinia_transcriptomics_3-19-20")
system('ls')

fdrcutoff<-0.1
```
FDR cut-off for significance is `r fdrcutoff`.

```{r parseOF}
# parse OrthoFinder format to annotate with Human Gene Symbols
parse_orthogroups <- function(path_2_ogroups)
{
  orthogroups <- scan(path_2_ogroups, what = "",
                      skip = 1, sep = "\n")
  
  ### Not sure why some values are separated by tab in file
  orthogroups <- gsub("\t", ", ",
                      orthogroups)
  
  orthogroups <- strsplit(orthogroups, ", ")
  
  ### names of orthogroup are read in first list element
  names(orthogroups) <- sapply(orthogroups,
                               function(i) i[1])
  orthogroups <- lapply(orthogroups,
                        function(i) i[-1])
  
  ## Dont know why some elements in orthogroups are null ( "" )
  orthogroups <- lapply(orthogroups,
                        function(i) i[i != ""])
  return(orthogroups)
}

if (!file.exists("meltedOG.Rds")){
  OGlist<-parse_orthogroups("Orthogroups_5-11-20.tsv")
  system("ls")
  meltedOG<-melt(OGlist)
  #very slow, save in case R session aborts
  saveRDS(meltedOG, "meltedOG.Rds")
  rm(OGlist) #to release memory
  }else{
  meltedOG<-readRDS("meltedOG.Rds")
  } 

#check memory consumption
for (obj in ls()) { message(obj); print(object.size(get(obj)), units='auto') }


library(varhandle)
meltedOG$value<-unfactor(meltedOG$value) #works
head(meltedOG)
str(meltedOG)
names(meltedOG)<-c("seqid","OG")
head(meltedOG)

```

### GeneGlobe apoptosis gene-set, blasted for *Homo* hits
```{r map_OrthoFinderIDs_2_humanIDs}
#use Human ref_blastout to subset only apoptosis OGs from OGlist
#links gene_acc to unique OrthoFinder seqid
refblast<-read.table("Homo.fa_ref_blastout_sens_percep_light_stim",header=F,stringsAsFactors = F)
head(refblast) 
names(refblast)[1:2]<-c("gene_acc","seqid")

#link gene_acc to gene symbol (human)
homo_symbols<-read.table("gene_symbol_accid_sens_percep_light_stim",header=F,stringsAsFactors = F) 
names(homo_symbols)<-c("symbol","gene_acc") 

library(dplyr)
#link apoptosis gene accs to OGs
apo_OGs_acc<-inner_join(refblast[,1:2],meltedOG,by="seqid")
colnames(apo_OGs_acc)
head(apo_OGs_acc)
nrow(apo_OGs_acc) 
#should have: gene_acc, seqid, OG

#links symbols to apoptosis gene accs and OGs
apo_OGs_acc_sym<-inner_join(apo_OGs_acc[,1:3],homo_symbols,by="gene_acc") 
colnames(apo_OGs_acc_sym)
#should have: gene_acc, seqid, OG, symbol
nrow(apo_OGs_acc_sym) 
head(apo_OGs_acc_sym)
unique(apo_OGs_acc_sym$OG)



#import OrthoFinder counts (All genes)
system("head Orthogroups.GeneCount_5-11-20.tsv")
all_OG_counts<-read.table("Orthogroups.GeneCount_5-11-20.tsv", header=T, stringsAsFactors = F,row.names=1) #18192 genes
all_OG_counts<-all_OG_counts[,colnames(all_OG_counts)!="Total"]
colnames(all_OG_counts)<-unlist(strsplit(colnames(all_OG_counts),split="[.]fa_ed"))
colnames(all_OG_counts)<-gsub(x=colnames(all_OG_counts),pattern="_.+", replacement="", perl=T)
colnames(all_OG_counts)<-gsub(x=colnames(all_OG_counts),pattern="actinula", replacement="Actinula", perl=T)
colnames(all_OG_counts)<-gsub(x=colnames(all_OG_counts),pattern="hydractinia", replacement="Planula_Hydractinia", perl=T)
colnames(all_OG_counts)<-gsub(x=colnames(all_OG_counts),pattern="Hsym.trinity.stringtie", replacement="Adult_Hydractinia", perl=T)
head(all_OG_counts)
# 
# #subset gene counts using apotosis OGs only
unique(apo_OGs_acc_sym$OG) 
apo_gene_counts<-all_OG_counts[rownames(all_OG_counts) %in% unique(apo_OGs_acc_sym$OG),]
unique(apo_OGs_acc_sym$OG) %in% rownames(apo_gene_counts) 
nrow(apo_gene_counts) 
head(apo_gene_counts)
# 
# #re-label OGs based on human gene label
apo_OGs_acc_sym$symbol[apo_OGs_acc_sym$OG %in% rownames(apo_gene_counts)]
apo_OGs_acc_sym<-apo_OGs_acc_sym[order(apo_OGs_acc_sym$OG),]
nrow(apo_OGs_acc_sym) 
z <- apo_OGs_acc_sym[!duplicated(apo_OGs_acc_sym$OG),]
nrow(z) 
# 
apo_counts_symbol<-apo_gene_counts; rownames(apo_counts_symbol)<-z$symbol[z$OG %in% rownames(apo_gene_counts)]
nrow(apo_counts_symbol) 
head(apo_counts_symbol)



#### Part 3: Get Species of Interest accids for OGs in gene set ###

#subset melted OG for species of interest
Hs_melted<-subset(meltedOG, grepl("^Hs_planula",meltedOG$seqid)) #works
#link human apoptosis apo_OGs_acc_sym to hydractinia (human OG to other species seqids)
hydract_acc_apo_OGs_acc_sym<-inner_join(apo_OGs_acc_sym[,1:4],Hs_melted,by="OG") #works
#rename cols:
names(hydract_acc_apo_OGs_acc_sym)[1:5]<- c("gene_acc", "Homo_seqid", "OG", "symbol", "Hydractinia_seqid")  #works
head(hydract_acc_apo_OGs_acc_sym)
nrow(hydract_acc_apo_OGs_acc_sym) #619

#Get original header for heatmap/salmon #almost
gene_acc_simple<-unlist(strsplit(hydract_acc_apo_OGs_acc_sym$Hydractinia_seqid,split="..", fixed = T))[c(T,F)] #split on .. and only keep first split objects

hydract_acc_apo_OGs_acc_sym$Hydractinia_seqid<-gene_acc_simple #change col items to new headers
head(hydract_acc_apo_OGs_acc_sym)

unique(hydract_acc_apo_OGs_acc_sym$OG)
unique(hydract_acc_apo_OGs_acc_sym$Hydractinia_seqid)
nrow(hydract_acc_apo_OGs_acc_sym) #619

write.table(hydract_acc_apo_OGs_acc_sym, "C:\\Desktop\\R\\Hydractinia_transcriptomics_3-19-20\\Reduced_Hs_Sensory_Percep_Light_Stim_R_output_genes.txt", sep="\t")


###Stop Here###
```
